# Generated by Django 4.1.4 on 2023-03-25 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='humans',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Time', models.CharField(max_length=20)),
                ('Date', models.CharField(max_length=20)),
                ('Total_Females', models.IntegerField()),
                ('Total_Males', models.IntegerField()),
                ('Total_attracted_humans', models.IntegerField()),
                ('Total_present_humans', models.IntegerField()),
            ],
        ),
    ]
